### ISSUE TITLE
Can't connect to a shares without a password and NOPASSWORDREQ

### ISSUE THREAD

**Issue by BSzili** [salass00/smb2fs#15]
If I don't specify a password for a folder shared with everyone and "Turn off password protected sharing" selected, I get a SMB2_STATUS_INVALID_PARAMETER error. E.g. "smb://host/folder NOPASSWORDREQ".

**Comment by salass00** [comment]
Does it help if you change the password parameter to '(password ? password : "")' in smb2_connect_share()?
