### ISSUE TITLE
smb2_connect_shared failed with v53.7

### ISSUE THREAD

**Issue by steen-lund** [salass00/smb2fs#17]
After updating to v53.7 I get a requester with the message:
smb2_connect_share failed
Session setup failed with (0xc000006d) STATUS_LOGON_FAILURE

my startup string is
"smb://192.168.1.4/public NOPASSWORDREQ VOLUME=NAS"

I have the guest account enabled on my Synology NAS and proper permissions to access smb and the public folder.

It works fine with V53.6.

**Comment by steen-lund** [comment]
Forgot to mention, I am using the m68k version on OS 3.2.2.1 with Roadshow as TCP stack

**Comment by steen-lund** [comment]
Fixed on latest master

**Comment by myount** [comment]
In case anyone else comes across this and, like me, isn't set up to cross-compile amiga-m68k binaries and doesn't especially want to go to the trouble: this appears to only impact the '020 build of 53.7, as I have an Amiga with a plain 68k where `smb2-handler` works perfectly.  If you copy `smb-handler.000` over top of the installed '020 version (or install in expert mode and select the 68000 version explicitly from the jump), you will be able to connect to shares.  I'm sure using the plain 68k build will probably have some kind of performance impact, but it's not like any 68k series processor is a speed demon by modern standards anyway.

**Comment by Trotter73** [comment]
@myount Thanks for the tip, I'm not able to compile myself so this was a proper life line. Strange though that the 020 version worked OK on my PiStorm A1200 but not my Blizzard 1260, spent hours trying to diagnose this lol.
